# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint, Coverage, and Test

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install tox
      run: pip install tox
    - name: Run flake8
      run: tox -e lint
    - name: Run coverage
      run: tox -e coverage

  build:
    needs: pre-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: pip install tox
    - name: Run package tests
      run: tox -e py
